name: chatty
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
#  simple_permissions: ^0.1.9
  file_utils: ^0.1.4
  dio: ^3.0.10

  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.5.0


  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.0.0
  firebase_messaging: ^7.0.2
  flutter_local_notifications: 1.4.4+5

  firebase_auth: ^0.18.1+1
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.1+2
  firebase_database: ^4.0.0

#  sign_in_with_apple: ^2.5.2
  apple_sign_in: ^0.1.0
#  flutter_webview_plugin: ^0.3.10+1
  flutter_facebook_login: ^3.0.0
#  flutter_facebook_auth: ^0.3.2
  google_sign_in: ^4.5.4
#  provider: ^4.3.2+2

  cached_network_image: ^2.0.0
  flutter_slidable: ^0.5.4
  qr_flutter: ^3.2.0
  path_provider: ^1.6.14
  barcode_scan: ^3.0.1
  qr_mobile_vision: ^1.0.2
  flutter_datetime_picker: ^1.4.0
  flutter_staggered_grid_view: ^0.3.2
  photo_view: ^0.10.2
  shared_preferences: ^0.5.10
  image: ^2.1.12
  photo: ^0.4.8
  file_picker: ^2.0.0

#  flutter_audio_recorder: ^0.5.5
#  file: ^5.0.4
#  audioplayers: ^0.13.2
#  flutter_sound: ^6.0.1
#  audio_recorder: ^1.0.2


  image_picker: ^0.6.3+4
  multi_image_picker: ^4.7.13
  country_list_pick: ^1.0.0+5
  video_player: ^0.11.0
#  neeko: ^0.0.10
#  video_thumbnail: ^0.2.2
  flutter_sound: ^6.0.1

#  google_maps_place_picker: ^0.10.0

#  location: ^1.4.1
  google_map_location_picker: ^3.3.5
#  intl: ^0.16.1
#  intl_translation: ^0.17.10
#  google_maps_flutter: ^0.5.33
#  geolocator: ^6.0.0+4
#  flutter_google_places: ^0.2.6

  permission_handler: ^5.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/ic_nav_main/icon-home.png
    - assets/images/ic_nav_main/icon-chat.png
    - assets/images/ic_nav_main/icon-moments.png
    - assets/images/ic_nav_main/icon-me.png
    - assets/images/ic_nav_main/menubar_home-ac@2x.png
    - assets/images/ic_nav_main/menubar_home@2x.png
    - assets/images/ic_nav_main/menubar_chat-ac@2x.png
    - assets/images/ic_nav_main/menubar_chat@2x.png
    - assets/images/ic_nav_main/menubar_moment-ac@2x.png
    - assets/images/ic_nav_main/menubar_moment@2x.png
    - assets/images/ic_nav_main/menubar_discovery-ac@2x.png
    - assets/images/ic_nav_main/menubar_discovery@2x.png
    - assets/images/icons/icon-member.png
    - assets/images/icons/icon-back.png
    - assets/images/icons/loadingimg.png
    - assets/images/demo/marketing.png
    - assets/images/icons/icon-drop-down.png
    - assets/images/icons/icon-drop-up.png
    - assets/images/icons/icon-drop-right.png
    - assets/images/icons/icon-qr-code.png
    - assets/images/icons/loadingimg.png
    - assets/images/icons/icons-call.png
    - assets/images/icons/icons-chat.png
    - assets/images/icons/icons-video-message.png
    - assets/images/demo/user-icon.webp
    - assets/images/demo/blog-thumb.jpg
    - assets/images/demo/demo-bg.png
    - assets/images/bg-splash-screen.png
    - assets/images/bg-profile.png
    - assets/images/icons/ic-emoji-btn.png
    - assets/images/icons/icon-noti.png
    - assets/images/icons/icon-qr.png
    - assets/images/icons/icon-lang.png
    - assets/images/icons/icon-picn-video.png
    - assets/images/icons/icon-pass.png
    - assets/images/icons/icon-moment.png
    - assets/images/icons/icon-about.png
    - assets/images/icons/icon-close.png
    - assets/images/icons/icon-calendar.png
    - assets/images/icons/icon-send.png
    - assets/images/icons/icon-add-groups.png
    - assets/images/icons/icon-add-friends.png
    - assets/images/icons/icon-setting.png
    - assets/images/icons/icon-loading.png
    - assets/images/icons/icon-logo&text.png
    - assets/images/icons/apple_logo_black.png
    - assets/images/icons/apple_logo_white.png
    - assets/images/icons/google-logo.png
    - assets/images/icons/icon_name.png
    - assets/images/icons/icon_@.png
    - assets/images/icons/icon_telephone.png
    - assets/images/icons/icon_key.png
    - assets/images/icons/icon_lock.png
    - assets/images/icons/more.png
    - assets/images/icons/location.png
    - assets/images/icons/contact.png
    - assets/images/icons/files.png
    - assets/images/icons/audio.png
    - assets/images/icons/photo_video.png
    - assets/images/icons/search-by-qr-code.png
    - assets/images/icons/icon-sticker.png
    - assets/images/icons/icon-service.png
    - assets/images/icons/icon-officials.png
    - assets/images/icons/icon-friend.png
    - assets/images/icons/icon-group.png
    - assets/images/icons/icon-sms-phone.png
    - assets/images/icons/icon-sheard.png
    - assets/images/icons/icon-download.png
    - assets/images/icons/icon-comingsoon.png
    - assets/images/icons/icon-add-contact.png
    - assets/images/icons/img_not_available.jpeg
    - assets/images/icons/icon-search-not.png
    - assets/images/icons/icons_mic.png
    - assets/images/icons/background_recorder.png
    - assets/images/icons/icon-select-mic.png
    - assets/images/icons/icon-unselect-mic.png
    - assets/images/logo/ic_launcher.png
    - assets/images/logo/ic_launcher_round.png
    - assets/images/logo/rectangle.png
    - assets/images/logo/logo-2.png
    - assets/images/official/1@2x.png
    - assets/images/official/2@2x.png
    - assets/images/official/3@2x.png
    - assets/images/official/4@2x.png
    - assets/images/official/5@2x.png
    - assets/images/official/6@2x.png
    - assets/images/ic-sticker/mimi1.gif
    - assets/images/ic-sticker/mimi2.gif
    - assets/images/ic-sticker/mimi3.gif
    - assets/images/ic-sticker/mimi4.gif
    - assets/images/ic-sticker/mimi5.gif
    - assets/images/ic-sticker/mimi6.gif
    - assets/images/ic-sticker/mimi7.gif
    - assets/images/ic-sticker/mimi8.gif
    - assets/images/ic-sticker/mimi9.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
